version: '3.8'

services:
  node-app:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install &&
             node index.js"
    depends_on:
      clickhouse:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=8123

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password123
      - CLICKHOUSE_DB=default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  clickhouse_data: